export interface PracticeProblem {
  id: number;
  platform: "LeetCode" | "GeeksforGeeks" | "Coding Ninjas" | "HackerRank";
  problem: string;
  difficulty: "Easy" | "Medium" | "Hard";
  companies: string[];
  link: string;
  tags: string[];
}

export const PRACTICE_PROBLEMS: PracticeProblem[] = [
  {
    id: 1,
    platform: "LeetCode",
    problem: "N-Queens (#51)",
    difficulty: "Hard",
    companies: ["Google", "Meta", "Amazon", "Microsoft", "Apple"],
    link: "https://leetcode.com/problems/n-queens/",
    tags: ["Backtracking", "Bitmask", "Array"],
  },
  {
    id: 2,
    platform: "LeetCode",
    problem: "N-Queens II (#52)",
    difficulty: "Hard",
    companies: ["Google", "Amazon", "Adobe", "Uber"],
    link: "https://leetcode.com/problems/n-queens-ii/",
    tags: ["Backtracking", "Bitmask"],
  },
  {
    id: 3,
    platform: "GeeksforGeeks",
    problem: "N-Queen Problem",
    difficulty: "Hard",
    companies: ["Flipkart", "Amazon", "Accolite", "Microsoft", "Samsung"],
    link: "https://www.geeksforgeeks.org/problems/n-queen-problem0315/1",
    tags: ["Recursion", "Backtracking"],
  },
  {
    id: 4,
    platform: "Coding Ninjas",
    problem: "N-Queens Studio",
    difficulty: "Hard",
    companies: ["Tower Research", "Cisco", "Goldman Sachs"],
    link: "https://www.naukri.com/code360/problems/n-queens_759332",
    tags: ["Backtracking", "Matrix"],
  },
  {
    id: 5,
    platform: "HackerRank",
    problem: "Crossword Puzzle Backtracking",
    difficulty: "Medium",
    companies: ["Bloomberg", "Arista Networks"],
    link: "https://www.hackerrank.com/challenges/crossword-puzzle/problem",
    tags: ["Backtracking", "Grid"],
  },
  {
    id: 6,
    platform: "LeetCode",
    problem: "Sudoku Solver (#37)",
    difficulty: "Hard",
    companies: ["Google", "Microsoft", "Snapchat", "DoorDash"],
    link: "https://leetcode.com/problems/sudoku-solver/",
    tags: ["Backtracking", "Matrix", "Bitmask"],
  },
  {
    id: 7,
    platform: "LeetCode",
    problem: "Valid Sudoku (#36)",
    difficulty: "Medium",
    companies: ["Amazon", "Apple", "Uber", "Yahoo"],
    link: "https://leetcode.com/problems/valid-sudoku/",
    tags: ["Hash Table", "Matrix"],
  },
  {
    id: 8,
    platform: "LeetCode",
    problem: "Word Search (#79)",
    difficulty: "Medium",
    companies: ["Meta", "Amazon", "Bloomberg", "TikTok"],
    link: "https://leetcode.com/problems/word-search/",
    tags: ["Backtracking", "Matrix", "DFS"],
  },
  {
    id: 9,
    platform: "LeetCode",
    problem: "Word Search II (#212)",
    difficulty: "Hard",
    companies: ["Google", "Amazon", "Microsoft", "Airbnb"],
    link: "https://leetcode.com/problems/word-search-ii/",
    tags: ["Trie", "Backtracking", "Matrix"],
  },
  {
    id: 10,
    platform: "GeeksforGeeks",
    problem: "Rat in a Maze Problem - I",
    difficulty: "Medium",
    companies: ["Amazon", "Microsoft", "Adobe", "Intuit"],
    link: "https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
    tags: ["Backtracking", "DFS", "Recursion"],
  },
  {
    id: 11,
    platform: "Coding Ninjas",
    problem: "Sudoku Solver Grid",
    difficulty: "Hard",
    companies: ["Infosys", "Wipro", "TCS"],
    link: "https://www.naukri.com/code360/problems/sudoku-solver_699919",
    tags: ["Backtracking", "Grid"],
  },
  {
    id: 12,
    platform: "LeetCode",
    problem: "Permutations (#46)",
    difficulty: "Medium",
    companies: ["Google", "Meta", "LinkedIn", "ByteDance"],
    link: "https://leetcode.com/problems/permutations/",
    tags: ["Backtracking", "Array"],
  },
  {
    id: 13,
    platform: "LeetCode",
    problem: "Permutations II (Unique) (#47)",
    difficulty: "Medium",
    companies: ["Amazon", "Oracle", "VMware"],
    link: "https://leetcode.com/problems/permutations-ii/",
    tags: ["Backtracking", "Sorting"],
  },
  {
    id: 14,
    platform: "LeetCode",
    problem: "Combination Sum (#39)",
    difficulty: "Medium",
    companies: ["Airbnb", "Meta", "Salesforce", "Atlassian"],
    link: "https://leetcode.com/problems/combination-sum/",
    tags: ["Backtracking", "Array"],
  },
  {
    id: 15,
    platform: "LeetCode",
    problem: "Palindrome Partitioning (#131)",
    difficulty: "Medium",
    companies: ["Google", "Bloomberg", "Cisco"],
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    tags: ["String", "Dynamic Programming", "Backtracking"],
  },
  {
    id: 16,
    platform: "GeeksforGeeks",
    problem: "M-Coloring Problem",
    difficulty: "Medium",
    companies: ["Oyo Rooms", "Samsung", "SAP Labs"],
    link: "https://www.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1",
    tags: ["Graph Coloring", "Backtracking"],
  },
  {
    id: 17,
    platform: "HackerRank",
    problem: "Recursive Digit Sum & Queens",
    difficulty: "Easy",
    companies: ["Visa", "Mastercard"],
    link: "https://www.hackerrank.com/challenges/recursive-digit-sum/problem",
    tags: ["Recursion", "Math"],
  },
  {
    id: 18,
    platform: "LeetCode",
    problem: "Subsets (#78)",
    difficulty: "Medium",
    companies: ["Amazon", "Google", "Meta", "Twilio"],
    link: "https://leetcode.com/problems/subsets/",
    tags: ["Bit Manipulation", "Backtracking"],
  },
  {
    id: 19,
    platform: "LeetCode",
    problem: "Letter Combinations of a Phone Number (#17)",
    difficulty: "Medium",
    companies: ["Google", "Amazon", "Uber", "Lyft"],
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    tags: ["Hash Table", "String", "Backtracking"],
  },
  {
    id: 20,
    platform: "Coding Ninjas",
    problem: "Knight's Tour Problem",
    difficulty: "Hard",
    companies: ["DE Shaw", "Directi"],
    link: "https://www.naukri.com/code360/problems/knight-tour_1170518",
    tags: ["Backtracking", "Chess"],
  },
  {
    id: 21,
    platform: "GeeksforGeeks",
    problem: "Solve the Sudoku Grid",
    difficulty: "Hard",
    companies: ["Amazon", "MakeMyTrip", "Paytm"],
    link: "https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1",
    tags: ["Backtracking", "Matrix"],
  },
  {
    id: 22,
    platform: "LeetCode",
    problem: "Matchsticks to Square (#473)",
    difficulty: "Medium",
    companies: ["Google", "Meta"],
    link: "https://leetcode.com/problems/matchsticks-to-square/",
    tags: ["Bitmask", "Dynamic Programming", "Backtracking"],
  },
];
